### ISSUE TITLE
ASM: 'network application-gateway import-file' giving error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#286] opened 2015-06-08 11:37 UTC
Please find the attached screenshot for the same.
![image](https://cloud.githubusercontent.com/assets/10084788/8033965/dd38195e-0e00-11e5-8b37-993d79b06833.png)

**Comment by romangromov** [comment] 2015-06-08 11:44
Please attach xml configuration file used in this case

**Comment by HimanshuBri** [comment] 2015-06-08 11:49
Cannot attach xml configuration file. Not supported. 
Below i have mentioned the contents of xml file.
{"backendAddressPools":[],"backendHttpSettingsList":[],"frontendIPConfigurations":[],"frontendPorts":[],"httpListeners":[],"httpLoadBalancingRules":[]}

**Comment by romangromov** [comment] 2015-06-08 11:56
* sorry, `JSON` file, of course (XML is used in PowerShell analog). We can not set an empty configuration for an existing app gateway - it's by design on server side. All configuration objects (backend address pools, http settings, etc.) must contains at least one object.

Attaching JSON configuration as good point to start with:

```json
{
    "backendAddressPools": [{
        "backendServers": [{
            "iPAddress": "10.0.0.1"
        }],
        "name": "pool1"
    }, {
        "backendServers": [{
            "iPAddress": "10.0.0.2"
        }],
        "name": "MyPool"
    }],
    "backendHttpSettingsList": [{
        "name": "setting1",
        "port": 80,
        "protocol": "Http",
        "cookieBasedAffinity": "Enabled"
    }, {
        "name": "MySettings",
        "port": 81,
        "protocol": "Http",
        "cookieBasedAffinity": "Enabled"
    }, {
        "name": "settings2",
        "port": 888,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled"
    }, {
        "name": "settings3",
        "port": 999,
        "protocol": "Http",
        "cookieBasedAffinity": "Disabled"
    }],
    "frontendIPConfigurations": [{
        "name": "fip1",
        "type": "Private",
        "staticIPAddress": "10.0.0.10"
    }],
    "frontendPorts": [{
        "name": "fep1",
        "port": 80
    }],
    "httpListeners": [{
        "name": "listener1",
        "frontendPort": "fep1",
        "protocol": "Http"
    }],
    "httpLoadBalancingRules": [{
        "name": "rule1",
        "type": "Basic",
        "backendHttpSettings": "setting1",
        "listener": "listener1",
        "backendAddressPool": "pool1"
    }]
}
```

**Comment by romangromov** [comment] 2015-06-08 12:01
@HimanshuBri you are right, error message is not clear enough, but we have to go with it.  
Comment from Kapil, who owns server side implementation: `SetConfig  is failing as you are using empty config`
Adding @anuchandy to confirm it's external and no action required from our side

**Comment by HimanshuBri** [comment] 2015-06-08 12:01
@romangromov. Thanks. Working fine when using above content.

**Comment by romangromov** [comment] 2015-06-08 12:02
@HimanshuBri please, let me know if you have any questions on this, you are always welcome!

**Comment by HimanshuBri** [comment] 2015-06-08 12:19
@romangromov. Thanks. I feel we can close this issue as i was using wrong xml file.

**Comment by romangromov** [comment] 2015-06-08 12:20
@HimanshuBri let's wait confirmation from @anuchandy at first

**Comment by HimanshuBri** [comment] 2015-06-08 12:20
@romangromov. Sure

**Comment by anuchandy** [comment] 2015-06-08 18:03
@HimanshuBri , @romangromov currently app gateway service returns "internal server error" if there is any error in the config we submit. We can hope server team will provide better error message before making the service public. I feel like we can close this issue.

**Closed** 2015-06-09 06:19 UTC

**Comment by romangromov** [comment] 2015-06-10 08:51
@HimanshuBri @anuchandy please note: I've re-worked `app gateway config` commands for better user experience (like it done in PowerShell) and one extra command `app gateway config show` was implemented as well
```
azure network application-gateway config export
azure network application-gateway config import
azure network application-gateway config show
```

**Comment by HimanshuBri** [comment] 2015-06-10 13:00
@romangromov. Thanks
