### ISSUE TITLE
ASM: 'network traffic-manager profile endpoint create' giving error

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#353] opened 2015-06-22 08:38 UTC
Please find the attached code snippet.<code><pre>E:\4486\22-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create Testtm Testdom1.trafficmanager.net TrafficManager -l westus
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the traffic manager profile "Testtm"
+ Looking up the traffic manager definition "Testtm"
+ Creating endpoint Testdom1.trafficmanager.net for traffic manager profile "Testtm"
error:   The location must be specified for endpoints of types: Any, TrafficManager in a policy of type 'Performance'.
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed

E:\4486\22-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create Testtm Testdom1.trafficmanager.net TrafficManager -l eastus
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the traffic manager profile "Testtm"
+ Looking up the traffic manager definition "Testtm"
+ Creating endpoint Testdom1.trafficmanager.net for traffic manager profile "Testtm"
error:   The location must be specified for endpoints of types: Any, TrafficManager in a policy of type 'Performance'.
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed
</pre></code>

**Comment by MikhailTryakhov** [comment] 2015-06-23 09:39
Hi @HimanshuBri, sorry for delay - I have some problems with azure login - it would be fixed tomorrow.
As I can see that is a server-side error.
@anuchandy, please approve it - I assume there is a register error in these examples - but server returns wrong error message. I'll wait for your comments before adding 'external' tag.
Please let me know your thoughts.

**Comment by MikhailTryakhov** [comment] 2015-07-01 09:11
Hi @HimanshuBri I've resolved this issue. 
please review the latest code changes

**Comment by HimanshuBri** [comment] 2015-07-01 09:31
Please check the attached screenshot.
![a](https://cloud.githubusercontent.com/assets/10084788/8451602/14a273ae-2002-11e5-82d6-3fb9069980a1.png)

**Comment by MikhailTryakhov** [comment] 2015-07-01 12:30
@HimanshuBri  please review the latest commit - it contains fixes for this bug and one error message

**Comment by HimanshuBri** [comment] 2015-07-01 13:15
@MikhailTryakhov Please look into this error
<pre>
<code>
C:\June\1july\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create Testtm testtmpEp CloudService
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "Testtm"
+ Looking up the Traffic Manager definition "Testtm"
+ Creating endpoint testtmpEp for Traffic Manager profile "Testtm"
error:   The endpoint testtmpep does not belong to this subscription.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed
</code>
</pre>

**Comment by MikhailTryakhov** [comment] 2015-07-02 07:45
Hi @HimanshuBri 
the problem is that you have entered domain name as 'testtmpEp', not 'testtmpEp.trafficmanager.net'.
That's why this error message shows correctly. I'll communicate with @anuchandy  today and ask, should we change current error message to do it more clear.

**Comment by MikhailTryakhov** [comment] 2015-07-02 10:54
@HimanshuBri thank you for log.
This is the same error as in https://github.com/MSOpenTech/azure-xplat-cli/issues/336
I'll communicate about it with @anuchandy on the meeting today

**Comment by sreekanthbs** [comment] 2015-07-03 10:29
@MikhailTryakhov  i m able to create traffic-manger endpoint for type - Traffic-Manger.
But for type - CloudService getting error.Please find the error below
<pre>
<code>
C:\July\2july\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile show cliTestTmP3j
info:    Executing command network traffic-manager profile show
+ Looking up the Traffic Manager profile "cliTestTmP3j"
+ Looking up the Traffic Manager definition "cliTestTmP3j"
data:    Name                            : cliTestTmP3j
data:    Domain name                     : foobar.cloudapp.net.trafficmanager.net
data:    Status                          : Enabled
data:    TTL                             : 30
data:    Load balancing method           : Performance
data:    Monitor status                  : Inactive
data:    Monitors:
data:      Interval in seconds           : 30
data:      Timeout in seconds            : 10
data:      Tolerated number of failures  : 3
data:      Protocol                      : HTTPS
data:      Port                          : 30
data:      Verb                          : GET
data:      Relative path                 : /index.html
data:      Expected status code          : 200
info:    network traffic-manager profile show command OK

C:\July\2july\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create cliTestTmP3j foobar.cloudapp.net.trafficmanager.net Cloud
Service
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "cliTestTmP3j"
+ Looking up the Traffic Manager definition "cliTestTmP3j"
+ Creating endpoint foobar.cloudapp.net.trafficmanager.net for Traffic Manager profile "cliTestTmP3j"
error:   The endpoint foobar.cloudapp.net.trafficmanager.net does not belong to this subscription.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed


C:\July\2july\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create cliTestTmP3j testtmpEp.trafficmanager.net CloudService
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "cliTestTmP3j"
+ Looking up the Traffic Manager definition "cliTestTmP3j"
+ Creating endpoint testtmpEp.trafficmanager.net for Traffic Manager profile "cliTestTmP3j"
error:   The endpoint testtmpep.trafficmanager.net does not belong to this subscription.
info:    Error information has been recorded to C:\Users\sunil.kumar1\.azure\azure.err
error:   network traffic-manager profile endpoint create command failed

</code>
</pre>

**Comment by anuchandy** [comment] 2015-07-06 16:46
@sreekanthbs 

Please see point 1 below, in order to make cloud service endpoint working there needs to be an existing cloud service.

The endpoints are the services to which Traffic Manager is directing traffic. There are 4 endpoints types:
1. CloudService. This is what you chose. In this case, the must be of the form ‘foobar.cloudapp.net’ and the service ‘foobar.cloudapp.net’ must exist in the same subscription.
2. AzureWebsite. In this case must be of the form ‘foobar.azurewebsites.net’ in the same subscription and the website must be at the Standard or Premium tier
3. Any. In this case the can be any FQDN, but not within ‘azurewebsites.net’
4. TrafficManager. In this case, is the FQDN of a different Traffic Manager profile in the same subscription.

**Comment by sreekanthbs** [comment] 2015-07-08 08:06
@anuchandy yes its working fine now for CloudService type. Thanks .
<pre>
<code>
C:\July\2july\azure-xplat-cli-dev-asm-network>node bin/azure network traffic-manager profile endpoint create Testtm xplatttesttservicee.cloudapp.net CloudService -u E
nabled -e 3
info:    Executing command network traffic-manager profile endpoint create
+ Looking up the Traffic Manager profile "Testtm"
+ Looking up the Traffic Manager definition "Testtm"
warn:    --min-child-endpoint will be ignored for undefined endpoint type
+ Creating endpoint xplatttesttservicee.cloudapp.net for Traffic Manager profile "Testtm"
+ Looking up the Traffic Manager profile "Testtm"
+ Looking up the Traffic Manager definition "Testtm"
data:    Name                            : Testtm
data:    Domain name                     : testdom.trafficmanager.net
data:    Status                          : Enabled
data:    TTL                             : 30
data:    Load balancing method           : Performance
data:    Monitor status                  : CheckingEndpoints
data:    Monitors:
data:      Interval in seconds           : 30
data:      Timeout in seconds            : 10
data:      Tolerated number of failures  : 3
data:      Protocol                      : HTTPS
data:      Port                          : 30
data:      Verb                          : GET
data:      Relative path                 : /health.aspx
data:      Expected status code          : 200
info:    network traffic-manager profile endpoint create command OK

</code>
</pre>

**Comment by MikhailTryakhov** [comment] 2015-07-14 11:08
Hi @sreekanthbs  
could you please clarify, should we close this issue?

**Comment by sreekanthbs** [comment] 2015-07-14 12:35
@MikhailTryakhov Yes we can close this issue

**Closed** 2015-07-14 14:15 UTC
Labels: bug, network
