### ISSUE TITLE
ASM: 'vm endpoint create-multiple' : no longer handles default values (since v0.9.5)

### ISSUE THREAD

**Issue by mraber** [MSOpenTech/azure-xplat-cli#400] opened 2015-07-03 10:43 UTC
Before version 0.9.5, I was able to create multiple endpoints at once with a parameter like '80:8080,443:8443'.
Now, I have to specify all 11 values to create a basic endpoint.

Example:

```
$> azure vm endpoint \
    create-multiple --json \
    --dns-name newcloudservice \
    newvm \
    80:8080,443:8443
each endpoint configuration in the endpoints configuration should be of the form
       <public-port>:<local-port>:<protocol>:<idle-timeout>:<direct-server-return>:<probe-protocol>:<probe-port>:<probe-path>:<load-balanced-set-name>:<internal-load-balancer-name>:<load-balancer-distribution>
Error information has been recorded to azure.err
vm endpoint create-multiple command failed

**Comment by anuchandy** [comment] 2015-07-06 16:19
@mraber there is a change in the way we need to specify the multiple endpoints in the latest  version. If you are not specifying the optional attributes such as protocol, idle-timeout, you have to specify empty string for the same, for example instead of 80:8080 it needs to be 80:8080:::::::::

**Comment by mraber** [comment] 2015-07-08 10:01
Thanks for the answer. See Azure/azure-xplat-cli#1899 for my comment.

**Comment by ruslangabitov** [comment] 2015-08-18 17:29
Closing this as duplicate of https://github.com/Azure/azure-xplat-cli/issues/1899, since all the discussion is going there.

**Closed by ruslangabitov** 2015-08-18 17:29 UTC
Labels: compute
